In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##  Bracket Indexing and Selection

In [9]:
#Get a value at an index
arr[3]

3

In [10]:
#Get values in a range

In [16]:
# -1 in second number to get the last parameter
arr[1:4]

array([1, 2, 3])

## Broadcasting

In [18]:
#Setting a value with index range (broadcasting)
arr[0:5] = 100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
#Reseat array, we'll see why I had to reset in a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#Importantes notes on slices
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [63]:
arr_2d = np.array (([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [32]:
arr_2d[2][1]

35

In [37]:
arr_2d[][1]

SyntaxError: invalid syntax (735202579.py, line 1)

In [57]:
arr_2d[:,1]

array([10, 25, 35])

In [59]:
arr_2d[1,2]

30

In [61]:
# Getting individual element value
arr_2d[1,0]

20

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [76]:
# 2D array slicing
#Shape (2,2) from top right corner
arr_2d[0:3,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [77]:
arr_2d[0:3,1:2]

array([[10],
       [25],
       [40]])

In [80]:
arr_2d[0:3,2:]

array([[15],
       [30],
       [45]])

## Fancy Indexing

In [83]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [89]:
#Length of array
arr_length = arr2d.shape[1]

In [90]:
arr_length

NameError: name 'arr2d_length' is not defined

In [115]:
#Set up array
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [122]:
for i in range(arr_length):
    arr2d[i] = i
    
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### More Indexing Help

In [145]:
arr = np.arange(3,12)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [148]:
arr[2]


5

In [149]:
arr> 2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [140]:
bool_arr = arr>4

In [141]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [142]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [143]:
arr[arr>2]

array([3, 4, 5, 6, 7, 8, 9])

In [144]:
x = 3
arr [arr>x]

array([4, 5, 6, 7, 8, 9])