## From a Python List

#### We can create an array by directly converting a list or list of lists

In [12]:
my_list = [1,2,3]
print (my_list)

[1, 2, 3]


In [6]:
import numpy as np

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9][10,None,None]]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\d24642\AppData\Local\Temp\ipykernel_15060\4181440156.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_matrix = [[1,2,3],[4,5,6],[7,8,9]
C:\Users\d24642\AppData\Local\Temp\ipykernel_15060\4181440156.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_matrix = [[1,2,3],[4,5,6],[7,8,9]
C:\Users\d24642\AppData\Local\Temp\ipykernel_15060\4181440156.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_matrix = [[1,2,3],[4,5,6],[7,8,9]
C:\Users\d24642\AppData\Local\Temp\ipykernel_15060\4181440156.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  my_matrix = [[1,2,3],[4,5,6

TypeError: list indices must be integers or slices, not tuple

##2.2 Built-in Methodsval

#### There are lots of built-in ways to generate Arrays


In [25]:
np.arange(-50,101)

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
np.arange(1,101,0.5)

array([  1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,
         5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,
        10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
        14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,
        19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,
        23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,
        28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,  31.5,  32. ,
        32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,  36. ,  36.5,
        37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,  40.5,  41. ,
        41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,  45. ,  45.5,
        46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5,  50. ,
        50.5,  51. ,  51.5,  52. ,  52.5,  53. ,  53.5,  54. ,  54.5,
        55. ,  55.5,  56. ,  56.5,  57. ,  57.5,  58. ,  58.5,  59. ,
        59.5,  60. ,  60.5,  61. ,  61.5,  62. ,  62.5,  63. ,  63.5,
        64. ,  64.5,

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [38]:
np.linspace(-50,130,20)

array([-50.        , -40.52631579, -31.05263158, -21.57894737,
       -12.10526316,  -2.63157895,   6.84210526,  16.31578947,
        25.78947368,  35.26315789,  44.73684211,  54.21052632,
        63.68421053,  73.15789474,  82.63157895,  92.10526316,
       101.57894737, 111.05263158, 120.52631579, 130.        ])

### Matrix Identidade

In [39]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random

##### Numpy also has lots of ways to create random number arrays

### Rand

##### Creates an array of the give nshape and populate it with random samples from a uniform distribution over

In [41]:
np.random.rand(2)

array([0.67961155, 0.13606859])

In [47]:
np.random.rand(5,5)

array([[0.27554874, 0.79740741, 0.31476852, 0.21422442, 0.50577329],
       [0.98482948, 0.89053018, 0.3203989 , 0.44434828, 0.91138864],
       [0.37450896, 0.7800136 , 0.17124012, 0.70981396, 0.92589696],
       [0.62121539, 0.31900905, 0.65077933, 0.1947824 , 0.65653911],
       [0.4900548 , 0.4129565 , 0.86440312, 0.26594765, 0.0736595 ]])

### Randn - Normal Distribution

##### Returns a sample from the "stander normal" distribution. Unlinks rand which is uniform:

In [48]:
np.random.randn(10)

array([-0.84531098,  0.84909914,  0.58978958,  0.54610387, -0.22510703,
        0.14437365, -0.30269089, -0.49879669, -1.6939239 ,  1.65336613])

### radint

#### Return random integers from low (inclusive) to high (exclusive)

In [61]:
np.random.randint(1,51)

13

In [51]:
np.random.randint(1,100,3)

array([45, 22,  9])

## Array attributes and Methods

In [63]:
ar = np.arange(25)
ranar = np.random.randint(0,50,10)

In [64]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
ranar

array([ 4,  7, 41, 48, 38, 49, 14,  5, 35, 41])

## Reshape

In [66]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
ranar.reshape(5,2)

array([[ 4,  7],
       [41, 48],
       [38, 49],
       [14,  5],
       [35, 41]])

### max,min,argmax,argmin

In [73]:
ranar

array([ 4,  7, 41, 48, 38, 49, 14,  5, 35, 41])

In [74]:
ranar.max()

49

In [75]:
ranar.argmax()

5

In [77]:
ranar.min()

4

In [79]:
ranar.argmin()

0

## Shape

#### Shape is an attribute that arrays have (not a method):

In [81]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
#vector
ar.shape

(25,)

In [87]:
# Notice the two sets of brackets
ar.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [88]:
ar.reshape(1,25).shape

(1, 25)

In [90]:
ar.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [91]:
matrix = ar.reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
matrix.shape

(5, 5)

### dtype

#### You can also grab the data type of the object in the array

In [98]:
matrix.dtype

dtype('int32')

In [95]:
tipagem = np.linspace (1,100,20)

In [96]:
tipagem

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [99]:
tipagem.dtype

dtype('float64')